# Generated by Django 3.0.5 on 2020-04-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('status', models.CharField(choices=[('IN', 'Inactive'), ('CR', 'Critical'), ('RG', 'Regular'), ('NC', 'Nice')], default='IN', max_length=2)),
            ],
        ),
    ]
